# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_interface_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from final_graph_data_design import Ui_GraphWindow
import data_operations as do


class Ui_OptionsWindow(object):
    def setupUi(self, OptionsWindow):
        OptionsWindow.setObjectName("OptionsWindow")
        OptionsWindow.setEnabled(True)
        OptionsWindow.resize(850, 665)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OptionsWindow.sizePolicy().hasHeightForWidth())
        OptionsWindow.setSizePolicy(sizePolicy)
        OptionsWindow.setMinimumSize(QtCore.QSize(850, 665))
        OptionsWindow.setMaximumSize(QtCore.QSize(850, 665))
        self.centralwidget = QtWidgets.QWidget(OptionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gradoviBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gradoviBox.setGeometry(QtCore.QRect(600, 185, 200, 210))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.gradoviBox.setFont(font)
        self.gradoviBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gradoviBox.setAutoFillBackground(False)
        self.gradoviBox.setAlignment(QtCore.Qt.AlignCenter)
        self.gradoviBox.setObjectName("gradoviBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gradoviBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 161, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.vrijemeBox = QtWidgets.QGroupBox(self.centralwidget)
        self.vrijemeBox.setGeometry(QtCore.QRect(50, 50, 480, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.vrijemeBox.setFont(font)
        self.vrijemeBox.setAlignment(QtCore.Qt.AlignCenter)
        self.vrijemeBox.setObjectName("vrijemeBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.vrijemeBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 442, 430))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(40, -1, 215, 15)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pickDan = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.pickDan.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pickDan.setFont(font)
        self.pickDan.setWrapping(False)
        self.pickDan.setCalendarPopup(True)
        self.pickDan.setObjectName("pickDan")
        self.horizontalLayout_5.addWidget(self.pickDan)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.rasponRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rasponRadio.setFont(font)
        self.rasponRadio.setObjectName("rasponRadio")
        self.gridLayout.addWidget(self.rasponRadio, 8, 0, 1, 1)
        self.mjesecRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.mjesecRadio.setFont(font)
        self.mjesecRadio.setObjectName("mjesecRadio")
        self.gridLayout.addWidget(self.mjesecRadio, 4, 0, 1, 1)
        self.godinaRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.godinaRadio.setFont(font)
        self.godinaRadio.setObjectName("godinaRadio")
        self.gridLayout.addWidget(self.godinaRadio, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(40, -1, -1, 15)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setEnabled(False)
        self.label.setMaximumSize(QtCore.QSize(25, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.rasponOd = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.rasponOd.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rasponOd.setFont(font)
        self.rasponOd.setCalendarPopup(True)
        self.rasponOd.setObjectName("rasponOd")
        self.horizontalLayout_4.addWidget(self.rasponOd)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setEnabled(False)
        self.label_2.setMaximumSize(QtCore.QSize(25, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.rasponDo = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.rasponDo.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rasponDo.setFont(font)
        self.rasponDo.setCalendarPopup(True)
        self.rasponDo.setObjectName("rasponDo")
        self.horizontalLayout_4.addWidget(self.rasponDo)
        self.gridLayout.addLayout(self.horizontalLayout_4, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(40, -1, 215, 15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pickGodina = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.pickGodina.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pickGodina.setFont(font)
        self.pickGodina.setObjectName("pickGodina")
        self.pickGodina.addItem("")
        self.horizontalLayout_3.addWidget(self.pickGodina)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(40, -1, -1, 15)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pickMjesecMjesec = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.pickMjesecMjesec.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pickMjesecMjesec.setFont(font)
        self.pickMjesecMjesec.setObjectName("pickMjesecMjesec")
        self.pickMjesecMjesec.addItem("")
        self.horizontalLayout_2.addWidget(self.pickMjesecMjesec)
        self.pickMjesecGodina = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.pickMjesecGodina.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pickMjesecGodina.setFont(font)
        self.pickMjesecGodina.setObjectName("pickMjesecGodina")
        self.pickMjesecGodina.addItem("")
        self.horizontalLayout_2.addWidget(self.pickMjesecGodina)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.danRadio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.danRadio.setFont(font)
        self.danRadio.setObjectName("danRadio")
        self.gridLayout.addWidget(self.danRadio, 2, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 10, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(40, -1, -1, -1)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMaximum(12)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 1, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(31)
        self.spinBox.setProperty("value", 0)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 1, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setMaximum(12)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_2.addWidget(self.spinBox_3, 2, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setMaximum(31)
        self.spinBox_4.setProperty("value", 0)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_2.addWidget(self.spinBox_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setEnabled(False)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setEnabled(False)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setEnabled(False)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 11, 0, 1, 1)
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openDataWindow())
        self.confirmButton.setGeometry(QtCore.QRect(350, 580, 150, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmButton.sizePolicy().hasHeightForWidth())
        self.confirmButton.setSizePolicy(sizePolicy)
        self.confirmButton.setMinimumSize(QtCore.QSize(150, 35))
        self.confirmButton.setMaximumSize(QtCore.QSize(150, 35))
        self.confirmButton.setObjectName("confirmButton")
        OptionsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OptionsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 31))
        self.menubar.setObjectName("menubar")
        OptionsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OptionsWindow)
        self.statusbar.setObjectName("statusbar")
        OptionsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OptionsWindow)
        self.danRadio.toggled['bool'].connect(self.pickDan.setEnabled)
        self.mjesecRadio.toggled['bool'].connect(self.pickMjesecMjesec.setEnabled)
        self.mjesecRadio.toggled['bool'].connect(self.pickMjesecGodina.setEnabled)
        self.godinaRadio.toggled['bool'].connect(self.pickGodina.setEnabled)
        self.rasponRadio.toggled['bool'].connect(self.label.setEnabled)
        self.rasponRadio.toggled['bool'].connect(self.rasponOd.setEnabled)
        self.rasponRadio.toggled['bool'].connect(self.label_2.setEnabled)
        self.rasponRadio.toggled['bool'].connect(self.rasponDo.setEnabled)
        self.radioButton.toggled['bool'].connect(self.spinBox.setEnabled)
        self.radioButton.toggled['bool'].connect(self.spinBox_2.setEnabled)
        self.radioButton.toggled['bool'].connect(self.comboBox.setEnabled)
        self.radioButton.toggled['bool'].connect(self.spinBox_4.setEnabled)
        self.radioButton.toggled['bool'].connect(self.spinBox_3.setEnabled)
        self.radioButton.toggled['bool'].connect(self.comboBox_2.setEnabled)
        self.radioButton.toggled['bool'].connect(self.label_3.setEnabled)
        self.radioButton.toggled['bool'].connect(self.label_4.setEnabled)
        self.radioButton.toggled['bool'].connect(self.label_5.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(OptionsWindow)
        OptionsWindow.setTabOrder(self.danRadio, self.mjesecRadio)
        OptionsWindow.setTabOrder(self.mjesecRadio, self.godinaRadio)
        OptionsWindow.setTabOrder(self.godinaRadio, self.rasponRadio)
        OptionsWindow.setTabOrder(self.rasponRadio, self.checkBox)
        OptionsWindow.setTabOrder(self.checkBox, self.checkBox_2)
        OptionsWindow.setTabOrder(self.checkBox_2, self.checkBox_3)
        OptionsWindow.setTabOrder(self.checkBox_3, self.pickDan)
        OptionsWindow.setTabOrder(self.pickDan, self.pickMjesecMjesec)
        OptionsWindow.setTabOrder(self.pickMjesecMjesec, self.pickMjesecGodina)
        OptionsWindow.setTabOrder(self.pickMjesecGodina, self.pickGodina)
        OptionsWindow.setTabOrder(self.pickGodina, self.rasponOd)
        OptionsWindow.setTabOrder(self.rasponOd, self.rasponDo)

    def retranslateUi(self, OptionsWindow):
        _translate = QtCore.QCoreApplication.translate
        OptionsWindow.setWindowTitle(_translate("OptionsWindow", "MainWindow"))
        self.gradoviBox.setTitle(_translate("OptionsWindow", "Gradovi"))
        self.checkBox.setText(_translate("OptionsWindow", "Rijeka"))
        self.checkBox_2.setText(_translate("OptionsWindow", "Marčelji"))
        self.checkBox_3.setText(_translate("OptionsWindow", "Matulji"))
        self.vrijemeBox.setTitle(_translate("OptionsWindow", "Vrijeme"))
        self.pickDan.setDisplayFormat(_translate("OptionsWindow", "dd.MM.yyyy."))
        self.rasponRadio.setText(_translate("OptionsWindow", "Raspon"))
        self.mjesecRadio.setText(_translate("OptionsWindow", "Mjesec"))
        self.godinaRadio.setText(_translate("OptionsWindow", "Godina"))
        self.label.setText(_translate("OptionsWindow", "Od:"))
        self.rasponOd.setDisplayFormat(_translate("OptionsWindow", "dd.MM.yyyy."))
        self.label_2.setText(_translate("OptionsWindow", "Do:"))
        self.rasponDo.setDisplayFormat(_translate("OptionsWindow", "dd.MM.yyyy."))
        self.pickGodina.setItemText(0, _translate("OptionsWindow", "Godina"))
        self.pickMjesecMjesec.setItemText(0, _translate("OptionsWindow", "Mjesec"))
        self.pickMjesecGodina.setItemText(0, _translate("OptionsWindow", "Godina"))
        self.danRadio.setText(_translate("OptionsWindow", "Dan"))
        self.radioButton.setText(_translate("OptionsWindow", "Usporedba"))
        self.comboBox_2.setItemText(0, _translate("OptionsWindow", "-"))
        self.comboBox.setItemText(0, _translate("OptionsWindow", "-"))
        self.label_3.setText(_translate("OptionsWindow", "Dan"))
        self.label_4.setText(_translate("OptionsWindow", "Mjesec"))
        self.label_5.setText(_translate("OptionsWindow", "Godina"))
        self.confirmButton.setText(_translate("OptionsWindow", "Prikaži podatke"))
       
    def openDataWindow(self):
        if self.checkBox.isChecked():
            grad = self.checkBox.text()
            do.load_dataset("../data/Rijeka.csv", grad)
        if self.checkBox_2.isChecked():
            grad = self.checkBox_2.text()
            do.load_dataset("../data/Marcelji.csv", grad)
        if self.checkBox_3.isChecked():
            grad = self.checkBox_3.text()
            do.load_dataset("../data/Matulji.csv", grad)

        if self.danRadio.isChecked():
            datum = self.pickDan.text().split('.')
            value = do.get_day_value(grad, int(datum[0]), int(datum[1]), int(datum[2]))

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_GraphWindow()
        self.ui.setupUi(self.window)
        self.ui.label_2.setText(str(value))
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptionsWindow = QtWidgets.QMainWindow()
    ui = Ui_OptionsWindow()
    ui.setupUi(OptionsWindow)
    OptionsWindow.show()
    sys.exit(app.exec_())

