# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_graph_data_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GraphWindow(object):
    def setupUi(self, GraphWindow):
        GraphWindow.setObjectName("GraphWindow")
        GraphWindow.setEnabled(True)
        GraphWindow.resize(1000, 810)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GraphWindow.sizePolicy().hasHeightForWidth())
        GraphWindow.setSizePolicy(sizePolicy)
        GraphWindow.setMinimumSize(QtCore.QSize(1000, 810))
        GraphWindow.setMaximumSize(QtCore.QSize(1000, 810))
        GraphWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(GraphWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(50, 500, 250, 230))
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.labelMmax = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelMmax.setFont(font)
        self.labelMmax.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelMmax.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMmax.setObjectName("labelMmax")
        self.gridLayout.addWidget(self.labelMmax, 3, 0, 1, 1)
        self.labelYsum = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelYsum.setFont(font)
        self.labelYsum.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelYsum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelYsum.setObjectName("labelYsum")
        self.gridLayout.addWidget(self.labelYsum, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.labelMsum = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelMsum.setFont(font)
        self.labelMsum.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelMsum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMsum.setObjectName("labelMsum")
        self.gridLayout.addWidget(self.labelMsum, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.labelYmax = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelYmax.setFont(font)
        self.labelYmax.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelYmax.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelYmax.setObjectName("labelYmax")
        self.gridLayout.addWidget(self.labelYmax, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridFrame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.labelDif = QtWidgets.QLabel(self.gridFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDif.setFont(font)
        self.labelDif.setObjectName("labelDif")
        self.gridLayout.addWidget(self.labelDif, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridFrame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 1, 1, 1)
        self.Graf = QtWidgets.QGraphicsView(self.centralwidget)
        self.Graf.setGeometry(QtCore.QRect(50, 50, 600, 400))
        self.Graf.setMaximumSize(QtCore.QSize(800, 16777215))
        self.Graf.setObjectName("Graf")
        GraphWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GraphWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 31))
        self.menubar.setObjectName("menubar")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        GraphWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GraphWindow)
        self.statusbar.setObjectName("statusbar")
        GraphWindow.setStatusBar(self.statusbar)
        self.actionGraph = QtWidgets.QAction(GraphWindow)
        self.actionGraph.setCheckable(False)
        self.actionGraph.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionGraph.setObjectName("actionGraph")
        self.actionData = QtWidgets.QAction(GraphWindow)
        self.actionData.setObjectName("actionData")
        self.actionAll = QtWidgets.QAction(GraphWindow)
        self.actionAll.setObjectName("actionAll")
        self.menuExport.addAction(self.actionGraph)
        self.menuExport.addAction(self.actionData)
        self.menuExport.addAction(self.actionAll)
        self.menubar.addAction(self.menuExport.menuAction())

        self.retranslateUi(GraphWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphWindow)

    def retranslateUi(self, GraphWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphWindow.setWindowTitle(_translate("GraphWindow", "MainWindow"))
        self.labelMmax.setText(_translate("GraphWindow", "Maksimum mjesec:"))
        self.labelYsum.setText(_translate("GraphWindow", "Godišnje sume:"))
        self.label_4.setText(_translate("GraphWindow", "50"))
        self.labelMsum.setText(_translate("GraphWindow", "Mjesečne sume:"))
        self.label_6.setText(_translate("GraphWindow", "100"))
        self.labelYmax.setText(_translate("GraphWindow", "Maksimum godina:"))
        self.label_8.setText(_translate("GraphWindow", "500"))
        self.label_2.setText(_translate("GraphWindow", "20"))
        self.labelDif.setText(_translate("GraphWindow", "Sumarna razlika:"))
        self.label_10.setText(_translate("GraphWindow", "25"))
        self.menuExport.setTitle(_translate("GraphWindow", "Export"))
        self.actionGraph.setText(_translate("GraphWindow", "Graph"))
        self.actionGraph.setToolTip(_translate("GraphWindow", "Graph"))
        self.actionGraph.setStatusTip(_translate("GraphWindow", "Save only graph"))
        self.actionGraph.setShortcut(_translate("GraphWindow", "Ctrl+G"))
        self.actionData.setText(_translate("GraphWindow", "Data"))
        self.actionData.setStatusTip(_translate("GraphWindow", "Save only data"))
        self.actionData.setShortcut(_translate("GraphWindow", "Ctrl+D"))
        self.actionAll.setText(_translate("GraphWindow", "All"))
        self.actionAll.setStatusTip(_translate("GraphWindow", "Save all"))
        self.actionAll.setShortcut(_translate("GraphWindow", "Ctrl+A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphWindow = QtWidgets.QMainWindow()
    ui = Ui_GraphWindow()
    ui.setupUi(GraphWindow)
    GraphWindow.show()
    sys.exit(app.exec_())

